version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tefl-network

  redis:
    image: redis:6-alpine
    networks:
      - tefl-network

  # fastapi:
  #   build: ./fastapi_app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  #   env_file: .env
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - tefl-network

  # celery-worker:
  #   build: ./celery
  #   command: celery -A tasks worker --loglevel=info
  #   env_file: .env
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - tefl-network

  # celery-beat:
  #   build: ./celery
  #   command: celery -A tasks beat --loglevel=info
  #   env_file: .env
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - tefl-network

  scrapy:
    build: ./scrapy_app
    env_file: .env
    depends_on:
      - postgres
    networks:
      - tefl-network
    command: tail -f /dev/null  # Keep container running but don't auto-start spider

volumes:
  postgres_data:

networks:
  tefl-network: