version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tefl-network

  redis:
    image: redis:6-alpine
    networks:
      - tefl-network

  

  scrapy:
    build: ./scrapy_app
    env_file: .env
    environment:
      - PYTHONPATH=/scrapy_app
    depends_on:
      - postgres
    networks:
      - tefl-network
 
volumes:
  postgres_data:

networks:
  tefl-network: