
services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - tefl-network

  redis:
    image: redis:6-alpine
    networks:
      - tefl-network

  scrapy:
    build: ./scrapy_app
    env_file: .env
    environment:
      - PYTHONPATH=/scrapy_app
    depends_on:
      - postgres
    networks:
      - tefl-network

  celery_worker:
    build: ./scrapy_app
    env_file: .env
    environment:
      - PYTHONPATH=/scrapy_app
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - tefl-network

  celery_beat:
    build: ./scrapy_app
    env_file: .env
    environment:
      - PYTHONPATH=/scrapy_app
    command: celery -A tasks beat --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - tefl-network

  fastapi:
    build: ./fastapi_app
    env_file: .env
    ports:
      - "8000:8000"  # Expose port 8000 on the host
    depends_on:
      - postgres
    networks:
      - tefl-network
 
volumes:
  postgres_data:

networks:
  tefl-network: